services:

  # 数据库管理
  adminer:
    image: adminer:5
    volumes:
      - ./adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${DB_ADMINER_PORT}:8080
    environment: 
      - ADMINER_PLUGINS=tables-filter tinymce json-column
    depends_on: 
      - db

  # php-fpm
  php-fpm:
    image: docker-magento2-php82-fpm
    build: ./php-fpm
    depends_on:
      - db
      - redis
      - opensearch
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

  # cron
  cron:
    image: docker-magento2-php82-cron
    build: ./cron
    depends_on:
      - php-fpm
    restart: ${CONTAINER_RESTART}
    volumes:
      - ${APPLICATION}:/var/www/html:cached
    tty: true

  # php-composer，安装组键、发布到服务器等操作
  workspace:
    image: docker-magento2-php82-workspace
    build: ./workspace
    user: www-data
    working_dir: /var/www/html
    depends_on:
      - php-fpm
    volumes:
      - workspace-home:/var/www
      - ${APPLICATION}:/var/www/html:cached
      - ./:/var/www/.docker/
    ports:
      - ${WORKSPACE_SSH_PORT}:22
      - ${WORKSPACE_CODER_PORT}:8080
    tty: true
    
  # nginx
  nginx:
    image: nginx:1.28
    depends_on:
      - php-fpm
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_HTTP_PORT}:80"

  # redis
  redis:
    image: redis:7.2
    restart: ${CONTAINER_RESTART}
    volumes:
      - ./redis/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf

  # Varnish
  varnish:
    image: varnish:7.7
    depends_on:
      - nginx
      - cron
      - workspace
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment: 
      - VARNISH_SIZE
    ports:
      - "${VARNISH_PORT}:80"

  # DB
  db:
    image: mariadb:10.11
    restart: ${CONTAINER_RESTART}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/initdb.d/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}

  # Open Search
  opensearch:
    image: opensearchproject/opensearch:2.19.4
    restart: ${CONTAINER_RESTART}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  # Rabbit MQ
  rabbitmq:
    image: rabbitmq:4.1-management
    restart: ${CONTAINER_RESTART}
    hostname: rabbit-001
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}



volumes:
  workspace-home:
  opensearch-data:
  db-data:

